name: SummaryAI
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - absl-py=2.1.0
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - arrow-cpp=14.0.2
  - async-timeout=4.0.3
  - attrs=23.1.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - blas=1.0
  - blinker=1.6.2
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - cachetools=5.3.3
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - cryptography=42.0.5
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=11.3
  - cudatoolkit=11.3.1
  - cudnn=8.9.2.26
  - cupti=11.3.1
  - datasets=2.19.1
  - dill=0.3.8
  - expat=2.6.2
  - filelock=3.13.1
  - frozenlist=1.4.0
  - fsspec=2024.3.1
  - future=0.18.3
  - gflags=2.2.2
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - google-auth=2.29.0
  - google-auth-oauthlib=0.5.2
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - huggingface_hub=0.23.1
  - icu=73.1
  - idna=3.7
  - intel-openmp=2021.4.0
  - jinja2=3.1.3
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcurl=8.7.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libopenblas=0.3.21
  - libprotobuf=3.20.3
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libuuid=1.41.5
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - magma=2.7.0
  - markdown=3.4.1
  - markupsafe=2.1.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.15
  - ncurses=6.4
  - networkx=3.2.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - oauthlib=3.2.2
  - openssl=3.0.14
  - orc=1.7.4
  - packaging=23.2
  - pandas=2.2.2
  - pip=24.0
  - protobuf=3.20.3
  - pyarrow=14.0.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=4
  - pycparser=2.21
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pysocks=1.7.1
  - python=3.11.7
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - pytorch=2.3.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - s2n=1.3.27
  - sentencepiece=0.1.99
  - setuptools=69.5.1
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.45.3
  - sympy=1.12
  - tbb=2021.8.0
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.6.0
  - tk=8.6.14
  - tqdm=4.66.4
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - urllib3=2.2.1
  - utf8proc=2.6.1
  - werkzeug=3.0.3
  - wheel=0.43.0
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - joblib==1.4.2
      - keybert==0.8.5
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - pillow==10.3.0
      - pygments==2.18.0
      - regex==2024.5.15
      - rich==13.7.1
      - safetensors==0.4.3
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - sentence-transformers==3.0.1
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - transformers==4.41.2
